name: Terraform CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7  # Or your preferred version

      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y yq

      - name: Parse terraform.yml
        id: config
        run: |
          echo "TF_DIR=$(yq e '.terraform_dir' terraform.yml)" >> $GITHUB_ENV
          echo "TF_ACTIONS=$(yq e '.terraform_actions' terraform.yml)" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Apply
        run: terraform apply ${{ env.TF_ACTIONS }} -auto-approve
        working-directory: ${{ env.TF_DIR }}
